# server {
#     listen 80;
#     server_name develop.pistis-market.eu;

#     location / {
#         root /usr/share/nginx/html;
#         index index.html;
#         try_files $uri $uri/ /index.html;
#     }

#     location /assets/ {
#         alias /usr/share/nginx/html/assets/;
#         try_files $uri =404;
#         access_log off;
#         add_header Cache-Control "public, max-age=31536000, immutable";
#         add_header Access-Control-Allow-Origin *;
#     }

#     error_page 404 /404.html;
#     location = /404.html {
#         root /usr/share/nginx/html;
#     }

#     error_page 500 502 503 504 /50x.html;
#     location = /50x.html {
#         root /usr/share/nginx/html;
#     }
# }

server {
    listen         8080;
    server_name    develop.pistis-market.eu;

    gzip on;
    gzip_static on;
    gzip_disable "msie6";

    gzip_comp_level 6;
    gzip_min_length 1100;
    gzip_buffers 16 8k;
    gzip_proxied any;
    gzip_types
        text/plain
        text/css
        text/js
        text/xml
        text/javascript
        application/javascript
        application/json
        application/xml
        application/rss+xml
        image/svg+xml
        application/vnd.ms-fontobject
        font/eot
        font/otf
        font/ttf
        application/octet-stream;


    location / {

        try_files $uri $uri/ /index.html;

        root   /usr/share/nginx/html;
        index  index.html index.htm;

        location ~* \.(?:css|js|json)$ {
            try_files $uri =404;
            add_header Cache-Control "public, max-age=31536000, immutable";
            add_header Access-Control-Allow-Origin *;
        }

        location = /index.html {
            add_header Cache-Control "no-cache, no-store, must-revalidate";
            add_header Access-Control-Allow-Origin *;
        }
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
